spring.application.name=tfg
spring.profiles.active=prod

spring.config.activate.on-profile=prod

spring.datasource.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.udojqeioeixaxbsxwpfe
spring.datasource.password=DapagojoseAA
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false

spring.security.oauth2.client.registration.google.client-id=1075712410495-8m4l6e0f3dupiv4i957hlodvse19cdi9.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile